In [14]:
#imported Libraries
from sklearn.datasets import load_breast_cancer
from sklearn.impute import SimpleImputer
import numpy as np 
Brest_data=load_breast_cancer()
x_data=Brest_data.data
#y_target=Brest_data.target
#Applying Cleaning Data
ImputedModule=SimpleImputer(missing_values=np.nan,strategy='mean',verbose=1)
ImputedX=ImputedModule.fit_transform(x_data)
#ImputedY=ImputedModule.fit_transform(y_target)
print('\t\t The Data Of X After Make Cleaning \n',ImputedX[:10])
print('**'*30)
#print('\t\t The Target Data Of Y After Make Cleaning \n',y_target[:10])

		 The Data Of X After Make Cleaning 
 [[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e

c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\impute\_base.py:382: FutureWarning: The 'verbose' parameter was deprecated in version 1.1 and will be removed in 1.3. A warning will always be raised upon the removal of empty columns in the future version.
  warnings.warn(


In [7]:
#Second Example 
from sklearn.impute import SimpleImputer
data =[[1,2,0],[3,0,1],
       [5,0,0],[0,4,6],
       [5,0,0],[4,5,5]]
imp=SimpleImputer(missing_values=0,strategy='mean')
imp=imp.fit(data)
print(imp)
print('**'*30)
modified_data=imp.transform(data)
print(modified_data)
#=======================================================================
#Same Example But Using Different Strategy (Median)
from sklearn.impute import SimpleImputer
data1 =[[1,2,0],[3,0,1],
       [5,0,0],[0,4,6],
       [5,0,0],[4,5,5]]
imp1=SimpleImputer(missing_values=0,strategy='median')
imp1=imp1.fit(data1)
print(imp1)
print('**'*30)
modified_data1=imp1.transform(data1)
print(modified_data1)

SimpleImputer(missing_values=0)
************************************************************
[[1.         2.         4.        ]
 [3.         3.66666667 1.        ]
 [5.         3.66666667 4.        ]
 [3.6        4.         6.        ]
 [5.         3.66666667 4.        ]
 [4.         5.         5.        ]]
SimpleImputer(missing_values=0, strategy='median')
************************************************************
[[1. 2. 5.]
 [3. 4. 1.]
 [5. 4. 5.]
 [4. 4. 6.]
 [5. 4. 5.]
 [4. 5. 5.]]


In [15]:
#Another Example For Data Cleaning 
from sklearn.impute import SimpleImputer
import numpy as np            
data2 = [[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,6 ],
        [5,0,np.nan],
        [4,5,5]]
imp3=SimpleImputer(missing_values=np.nan,strategy='mean',verbose=1)
imp3=imp3.fit_transform(data2)
print('\t\t The Data Before Making Cleaning Is \n',np.array(data2))
print('***'*40)
print('\t\t The Data After Making Cleaning \n',imp3)

		 The Data Before Making Cleaning Is 
 [[ 1.  2. nan]
 [ 3. nan  1.]
 [ 5. nan  0.]
 [nan  4.  6.]
 [ 5.  0. nan]
 [ 4.  5.  5.]]
************************************************************************************************************************
		 The Data After Making Cleaning 
 [[1.   2.   3.  ]
 [3.   2.75 1.  ]
 [5.   2.75 0.  ]
 [3.6  4.   6.  ]
 [5.   0.   3.  ]
 [4.   5.   5.  ]]


c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\impute\_base.py:382: FutureWarning: The 'verbose' parameter was deprecated in version 1.1 and will be removed in 1.3. A warning will always be raised upon the removal of empty columns in the future version.
  warnings.warn(
