In [2]:
from sklearn.datasets import load_iris 
from sklearn.linear_model import LogisticRegression 
X,y=load_iris(return_X_y=True)
clf1=LogisticRegression(random_state=10,solver='lbfgs',max_iter=1000,C=0.5,tol=0.01)
clf2=LogisticRegression(random_state=10,solver='liblinear')
clf3=LogisticRegression(random_state=10,solver='saga')
clf1.fit(X,y)
clf1.predict(X[:10,:])
clf1.predict_proba(X[:10,:])
score=clf1.score(X,y)
print('The Score Of Data Is ==> ',score)
print('Number Of Iterations Is ==> ',clf1.n_iter_)
print('Number Of Classes Is ==> ',clf1.classes_)
#=================================================================================================================================
#CLF2 
#=============================================================
print('***'*30)
clf2.fit(X,y)
clf2.predict(X[:10,:])
clf2.predict_proba(X[:10,:])
score1=clf2.score(X,y)
print('The Score Of Data Is ==> ',score1)
print('Number Of Iterations Is ==> ',clf2.n_iter_)
print('Number Of Classes Is ==> ',clf2.classes_)
#=================================================================================================================================
#CLF3 
#=============================================================
print('***'*30)
clf3.fit(X,y)
clf3.predict(X[:10,:])
clf3.predict_proba(X[:10,:])
score2=clf3.score(X,y)
print('The Score Of Data Is ==> ',score2)
print('Number Of Iterations Is ==> ',clf3.n_iter_)
print('Number Of Classes Is ==> ',clf3.classes_)

The Score Of Data Is ==>  0.9666666666666667
Number Of Iterations Is ==>  [85]
Number Of Classes Is ==>  [0 1 2]
******************************************************************************************
The Score Of Data Is ==>  0.96
Number Of Iterations Is ==>  [7 7 6]
Number Of Classes Is ==>  [0 1 2]
******************************************************************************************
The Score Of Data Is ==>  0.9866666666666667
Number Of Iterations Is ==>  [100]
Number Of Classes Is ==>  [0 1 2]


c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


In [3]:
#Another Example For Hearts Dataset 
import pandas as pd     
import numpy as np 
import matplotlib.pyplot as plt   
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error
#==========================================================
#First Read Data 
#==========================================================
dataset = pd.read_csv('D:\\AI\\10 القسم العاشر  مكتبة سايكيتليرن Sklearn Library\\Materials\\Data\\2.2 Logistic Regression\\heart.csv')
print('\t\t Show 5 Rows From Data Is \n',dataset.head(5))
print('***'*30)
#Splitting Data To ==> X  & Y 
x_data =dataset.iloc[:,:-1]
y_target =dataset.iloc[:,-1]
print('\t\t The First 5 Rows From X Data \n',x_data.head(5))
print('***'*20)
print('\t\t The First 5 Rows From Y Target \n',y_target.head(5))
print('***'*20)


		 Show 5 Rows From Data Is 
    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
******************************************************************************************
		 The First 5 Rows From X Data 
    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0   

In [4]:
#Splitting My Data into Training Data & Test Data 
X_train,X_test,y_train,y_test = train_test_split(x_data,y_target,test_size=0.25,random_state=0)
print('\t\t The X Training Data Is \n',X_train[:3])
print('****'*20)
print('\t\t The X Test Data Is \n',X_test[:3])
print('****'*20)
print('\t\t The Y Training Data Is \n',y_train[:3])
print('****'*20)
print('\t\t The Y Test Data Is \n',y_test[:3])
print('****'*20)

		 The X Training Data Is 
      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
173   58    1   2       132   224    0        0      173      0      3.2   
261   52    1   0       112   230    0        1      160      0      0.0   
37    54    1   2       150   232    0        0      165      0      1.6   

     slope  ca  thal  
173      2   2     3  
261      2   1     2  
37       2   0     3  
********************************************************************************
		 The X Test Data Is 
      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
225   70    1   0       145   174    0        1      125      1      2.6   
152   64    1   3       170   227    0        0      155      0      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   

     slope  ca  thal  
225      0   0     3  
152      1   0     3  
228      1   0     3  
*************************************************************************

In [5]:
#Apply Standar Scaler Becuase All Values Is That Between -1 to 1 
sc =StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
print('\t\t The X Training Data Is \n',X_train[:5])
print('****'*20)
print('\t\t The X Test Data Is \n',X_test[:5])
print('****'*20)

		 The X Training Data Is 
 [[ 0.35256528  0.70243936  0.9870291   0.02020565 -0.43596979 -0.42695628
  -0.9825655   1.01189274 -0.72352604  1.72483977  0.96222601  1.22723311
   1.12135917]
 [-0.31068598  0.70243936 -0.91982712 -1.1409796  -0.32539421 -0.42695628
   0.89174012  0.45363971 -0.72352604 -0.92348745  0.96222601  0.25993479
  -0.45968761]
 [-0.08960223  0.70243936  0.9870291   1.06527237 -0.28853568 -0.42695628
  -0.9825655   0.66835241 -0.72352604  0.40067616  0.96222601 -0.70736353
   1.12135917]
 [ 0.46310716  0.70243936  1.94045721  2.69093172  0.4117763  -0.42695628
  -0.9825655  -0.19049841 -0.72352604  2.55244203 -2.27370441 -0.70736353
   1.12135917]
 [ 1.34744218  0.70243936 -0.91982712 -0.6765055  -0.34382347 -0.42695628
  -0.9825655  -0.87757907  1.38212026  1.22827842 -0.6557392   1.22723311
   1.12135917]]
********************************************************************************
		 The X Test Data Is 
 [[ 1.67906782  0.70243936 -0.91982712  0.77497606 -

In [10]:
#Applying Logestic Regression Model 
clss=LogisticRegression(random_state=0)
clss.fit(X_train,y_train)
#Predicting The Test Set Results 
y_pred1=clss.predict(X_test)
print('\t\t The Values Of Y Predictions \n',y_pred1)
print('***'*50)
#probability of all values
pr = clss.predict_proba(X_test)[0:10,:]
print('\t\t The Predictions Values Is \n',pr)
print('***'*50)
#probability of zeros
pr = clss.predict_proba(X_test)[0:10,0]
print('\t\t The Predictions Probabalities Values \n',pr)
print('***'*50)
#probability of ones
pr = clss.predict_proba(X_test)[0:10,1]
print('\t\t The Predictions Probabalities Values one Column \n',pr)
print('***'*50)
#  Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred1)
print('\tConfusion Matrix \n',cm) 
print('***'*50)
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(y_test, y_pred1))
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, y_pred1))
from sklearn.metrics import median_absolute_error
print(median_absolute_error(y_test, y_pred1)) 

		 The Values Of Y Predictions 
 [0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 0 0 1 1 1 0 1 1 1 1 0
 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0
 0 1]
******************************************************************************************************************************************************
		 The Predictions Values Is 
 [[0.96421264 0.03578736]
 [0.18275371 0.81724629]
 [0.18628997 0.81371003]
 [0.98171588 0.01828412]
 [0.88161474 0.11838526]
 [0.62175492 0.37824508]
 [0.93007085 0.06992915]
 [0.8983798  0.1016202 ]
 [0.99539398 0.00460602]
 [0.9973351  0.0026649 ]]
******************************************************************************************************************************************************
		 The Predictions Probabalities Values 
 [0.96421264 0.18275371 0.18628997 0.98171588 0.88161474 0.62175492
 0.93007085 0.8983798  0.99539398 0.9973351 ]
************************************************************************

In [11]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score , confusion_matrix
#Loaded Data 
iris = load_iris()
X = iris.data
y = iris.target
print('\t\tThe Matrix Of X Data Is \n',X[:10])
print('**'*60)
print('\t\t The Matrix Of Y Data Is \n',y[:])

		The Matrix Of X Data Is 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
************************************************************************************************************************
		 The Matrix Of Y Data Is 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
#Applying StratifiedKFold
#K = 5 
skf = StratifiedKFold(n_splits=5)
#Creating Predicted Matrix Conatin Same Shape Of Y Matrix 
predict=np.zeros(y.shape[0])
#Splitting Into Train & Test Data 
for train,test in skf.split(X,y):
    x_train=X[train]
    x_test=X[test]
    y_train=y[train]
    y_test=y[test]
    LogReg_Model =LogisticRegression()
    LogReg_Model.fit(x_train,y_train)
    result=LogReg_Model.predict(x_test)
    predict[test] = result  
    print('\t\t The Train Data Is \n',train)
    print('***'*30)
    print('\t\t The Test Data Is \n',test)
    print('***'*30)
    print('\t\t The Result Is \n',result)
    print('***'*30)
    print('The Accuracy Score Is ==>  ',accuracy_score(y_test,result))
    print('=======================================================================')
#=========================================================================================
#To Know Total Accuracy 
print('The Total Accuracy Is ==> ',accuracy_score(y,predict))
cm = confusion_matrix(y,predict)
print('\t\t The Confusion Matrix Is \n',cm)        

		 The Train Data Is 
 [ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
******************************************************************************************
		 The Test Data Is 
 [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]
******************************************************************************************
		 The Result Is 
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2]
*********************************************************************************

c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
