In [13]:
#Application Using Transform Method 
import numpy as np 
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
data = load_breast_cancer()
x_data = data.data
y_target = data.target        
print('\t\t The X Data Is \n',x_data[:4])
print('****'*40)
print('The Y Target Data Is ==> ',y_target[:35])

		 The X Data Is 
 [[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e

In [17]:
#Applying Function Transformer 
def fun1(z):
    #return np.log1p(z)
    return np.sqrt(z)
    #return np.power(z,4)
f=FunctionTransformer(func=fun1)
f.fit(x_data)
x_f=f.transform(x_data)
x_train,x_test,y_train,y_test=train_test_split(x_f,y_target,test_size=0.2)
#Applying Logestic Regresssion Model 
LogReg_Model = LogisticRegression()
LogReg_Model.fit(x_train,y_train)
result=LogReg_Model.predict(x_test)
print('The Accuracy Score Is  ==> ',accuracy_score(y_test,result))
cm = confusion_matrix(y_test,result)
print('The Confusion Matrix Is \n',cm)

The Accuracy Score Is  ==>  0.956140350877193
The Confusion Matrix Is 
 [[42  3]
 [ 2 67]]


c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
#Another Example Using Polynomial Features 
from sklearn.datasets import load_breast_cancer 
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split 
data1 = load_breast_cancer()
x_data1 =   data1.data           
y_target1 = data1.target    
print('\t\t The X Data Is \n ',x_data1[:4])
print('****'*50)
print('The Y Traget Data Is ==> ',y_target1[:35])
print('==='*30)
#Recall Polynomial Features 
poly = PolynomialFeatures(degree=4,include_bias=True)
poly.fit(x_data1)
x_poly=poly.transform(x_data1)
x1_train,x1_test,y1_train,y1_test=train_test_split(x_poly,y_target1,test_size=0.2)


		 The X Data Is 
  [[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425

In [8]:
#Applying Logestic Regression 
LogReg_Model3=LogisticRegression()
LogReg_Model3.fit(x1_train,y1_train)
result3 = LogReg_Model3.predict(x1_test)
print('The Accuracy Score Is ==> ',accuracy_score(y1_test,result3))
Cm3 = confusion_matrix(y1_test,result3)
print('****'*30)
print('\t\t The Confusion Matrix Is \n',Cm3)
print('***'*20)
names=poly.get_feature_names_out()
print('\t\t The Features Names \n ',names)

c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


The Accuracy Score Is ==>  0.37719298245614036
************************************************************************************************************************
		 The Confusion Matrix Is 
 [[43  0]
 [71  0]]
************************************************************
		 The Features Names 
  ['1' 'x0' 'x1' ... 'x28^2 x29^2' 'x28 x29^3' 'x29^4']


In [13]:
#Another Example Using Selected Features 
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectPercentile,f_classif,chi2
data2 = load_breast_cancer()
x2_data=data2.data
y2_target = data2.target        
Sel1 =SelectPercentile(score_func=chi2,percentile=20)
Sel2 =SelectPercentile(score_func=chi2,percentile=40)
Sel3=SelectPercentile(score_func=chi2,percentile=60)
Sel4=SelectPercentile(score_func=chi2,percentile=80)
Sel5=SelectPercentile(score_func=f_classif,percentile=20)
Sel1.fit(x2_data,y2_target)
#Sel2.fit(x2_data,y2_target)
#Sel3.fit(x2_data,y2_target)
#Sel4.fit(x2_data,y2_target)
#Sel5.fit(x2_data,y2_target)
selected_features=Sel1.transform(x2_data)
SFeatures=Sel1.get_support()
print('\t\t The Selected Features Is Equal \n',SFeatures)
print('***'*30)
#Splitting Into Data To Training & Test Data 
x2_train,x2_test,y2_train,y2_test=train_test_split(selected_features,y2_target,test_size=0.2)
LogReg_Model4=LogisticRegression()
LogReg_Model4.fit(x2_train,y2_train)
result4=LogReg_Model4.predict(x2_test)
print('The Accuracy Score Is ==> ',accuracy_score(y2_test,result4))
print('**'*20)
conf=confusion_matrix(y2_test,result4)
print('\t\t The Confusion Matrix Is \n',conf)



		 The Selected Features Is Equal 
 [False False  True  True False False False False False False False False
 False  True False False False False False False  True False  True  True
 False False False False False False]
******************************************************************************************
The Accuracy Score Is ==>  0.9298245614035088
****************************************
		 The Confusion Matrix Is 
 [[33  4]
 [ 4 73]]


In [14]:
#Another Example Using Selected Features 
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectPercentile,f_classif,chi2
data2 = load_breast_cancer()
x2_data=data2.data
y2_target = data2.target        
Sel1 =SelectPercentile(score_func=chi2,percentile=20)
Sel2 =SelectPercentile(score_func=chi2,percentile=40)
Sel3=SelectPercentile(score_func=chi2,percentile=60)
Sel4=SelectPercentile(score_func=chi2,percentile=80)
Sel5=SelectPercentile(score_func=f_classif,percentile=20)
Sel2.fit(x2_data,y2_target)
selected_features=Sel2.transform(x2_data)
SFeatures=Sel2.get_support()
print('\t\t The Selected Features Is Equal \n',SFeatures)
print('***'*30)
#Splitting Into Data To Training & Test Data 
x2_train,x2_test,y2_train,y2_test=train_test_split(selected_features,y2_target,test_size=0.2)
LogReg_Model4=LogisticRegression()
LogReg_Model4.fit(x2_train,y2_train)
result4=LogReg_Model4.predict(x2_test)
print('The Accuracy Score Is ==> ',accuracy_score(y2_test,result4))
print('**'*20)
conf=confusion_matrix(y2_test,result4)
print('\t\t The Confusion Matrix Is \n',conf)



		 The Selected Features Is Equal 
 [ True  True  True  True False False False False False False  True False
  True  True False False False False False False  True  True  True  True
 False False  True False False False]
******************************************************************************************
The Accuracy Score Is ==>  0.956140350877193
****************************************
		 The Confusion Matrix Is 
 [[48  3]
 [ 2 61]]


c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
#Another Example Using Selected Features 
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectPercentile,f_classif,chi2
data2 = load_breast_cancer()
x2_data=data2.data
y2_target = data2.target        
Sel3=SelectPercentile(score_func=chi2,percentile=60)
Sel3.fit(x2_data,y2_target)
selected_features=Sel3.transform(x2_data)
SFeatures=Sel2.get_support()
print('\t\t The Selected Features Is Equal \n',SFeatures)
print('***'*30)
#Splitting Into Data To Training & Test Data 
x2_train,x2_test,y2_train,y2_test=train_test_split(selected_features,y2_target,test_size=0.2)
LogReg_Model4=LogisticRegression()
LogReg_Model4.fit(x2_train,y2_train)
result4=LogReg_Model4.predict(x2_test)
print('The Accuracy Score Is ==> ',accuracy_score(y2_test,result4))
print('**'*20)
conf=confusion_matrix(y2_test,result4)
print('\t\t The Confusion Matrix Is \n',conf)



		 The Selected Features Is Equal 
 [ True  True  True  True False False False False False False  True False
  True  True False False False False False False  True  True  True  True
 False False  True False False False]
******************************************************************************************
The Accuracy Score Is ==>  0.9210526315789473
****************************************
		 The Confusion Matrix Is 
 [[41  4]
 [ 5 64]]


c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
#Another Example Using Selected Features 
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectPercentile,f_classif,chi2
data2 = load_breast_cancer()
x2_data=data2.data
y2_target = data2.target        
Sel5=SelectPercentile(score_func=f_classif,percentile=20)
Sel5.fit(x2_data,y2_target)
selected_features=Sel5.transform(x2_data)
SFeatures=Sel2.get_support()
print('\t\t The Selected Features Is Equal \n',SFeatures)
print('***'*30)
#Splitting Into Data To Training & Test Data 
x2_train,x2_test,y2_train,y2_test=train_test_split(selected_features,y2_target,test_size=0.2)
LogReg_Model4=LogisticRegression()
LogReg_Model4.fit(x2_train,y2_train)
result4=LogReg_Model4.predict(x2_test)
print('The Accuracy Score Is ==> ',accuracy_score(y2_test,result4))
print('**'*20)
#conf=confusion_matrix(y2_test,result4)
#print('\t\t The Confusion Matrix Is \n',conf)
print('===================================================================================')


		 The Selected Features Is Equal 
 [ True  True  True  True False False False False False False  True False
  True  True False False False False False False  True  True  True  True
 False False  True False False False]
******************************************************************************************
The Accuracy Score Is ==>  0.9298245614035088
****************************************


c:\Users\Alhou\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
